version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo installing serverless 
      - npm install -g serverless
  pre_build:
    commands:
      - aws sts get-caller-identity
      - echo install source NPM dependencies
      - npm install
  build:
    commands:
      - echo displaying credentials
      - aws sts get-caller-identity
      - echo deployment started on `date`
      - echo deploying with the serverless framework
      - sls deploy -v -s prod
  post_build:
    commands:
      - echo Deployment completed on `date`           