version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo installing serverless 
      - npm install -g serverless
  pre_build:
    commands:
      - aws sts get-caller-identity
      - echo install source NPM dependencies
      - npm install
  build:
    commands:
      - setting credentials
      - credentials=$(aws sts assume-role --role-arn arn:aws:iam::731747136560:role/playground-role --role-session-name "RoleSessionFromCodeBuild" | jq .Credentials)
      - export AWS_ACCESS_KEY_ID=$(echo ${credentials} | jq -r .AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo ${credentials} | jq -r .SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo ${credentials} | jq -r .SessionToken)
      - aws sts get-caller-identity
      - echo deployment started on `date`
      - echo deploying with the serverless framework
      - sls deploy -v -s prod
  post_build:
    commands:
      - echo Deployment completed on `date`           