
service: vicente-serverles-dynamo

plugins:
  - serverless-offline

custom:
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - app_user_id
    - app_user_name

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    NOTES_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb;Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.NOTES_TABLE}"  
  profile: snap-portal-admin

functions:
  add-note:
    handler: api/add.handler
    description: POST /note
    events:
      - http:
          path: note
          method: post
          cors: 
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  update-note:
    handler: api/update.handler
    description: PATCH /note
    events:
      - http:
          path: note
          method: patch
          cors: 
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  get-notes:
    handler: api/getAll.handler
    description: GET /notes
    events:
      - http:
          path: notes
          method: get
          cors: 
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  get-note:
    handler: api/get.handler
    description: GET /note/n/{note_id}
    events:
      - http:
          path: note/n/{note_id}
          method: get
          cors: 
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  delete-note:
    handler: api/delete.handler
    description: DELETE /note/
    events:
      - http:
          path: note/t/{timestamp}
          method: delete
          cors: 
            origin: '*'
            headers: ${self:custom.allowedHeaders}
  


resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.NOTES_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
          - AttributeName: note_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: note_id-index
            KeySchema:
              - AttributeName: note_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1